title: Ibukunoluwa's Homepage
page-top-title: Ibukunoluwa Soyebo
top-section-bg-text: Computer Engineering
home-subtitle: Ibukunoluwa Soyebo&ensp;
copyright-text: '&copy; Ibukunoluwa Soyebo 2025. All Rights Reserved.'
